### ISSUE TITLE
Because first_app depends on stomp >=0.5.1 which requires SDK version <2.0.0, version solving failed.

### ISSUE THREAD

**Issue by eshiett1995** [rikulo/stomp#18]
i am new to flutter by the way, i tried using your library, but i got 
"The current Dart SDK version is 2.1.0-dev.5.0.flutter-a2eb050044."
"Because first_app depends on stomp >=0.5.1 which requires SDK version <2.0.0, version solving failed."

**Comment by tomyeh** [comment]
Please run `pub upgrade`

**Comment by eshiett1995** [comment]
where should i run the code, in the command line ? explain further. Cause i tried it in command line and got "pub is not a recognized command"
